# Services for HLK-LD2402

set_motion_threshold:
  fields:
    gate: int
    db_value: float
  required: [gate, db_value]
  
set_micromotion_threshold:
  fields:
    gate: int
    db_value: float
  required: [gate, db_value]

calibrate_with_coefficients:
  fields:
    trigger_coefficient: float
    hold_coefficient: float
    micromotion_coefficient: float
  required: [trigger_coefficient, hold_coefficient, micromotion_coefficient]
