external_components:
  - source:
      type: git
      url: https://github.com/mouldybread/hlk_ld2402_esphome
      ref: main

uart:
  id: uart_bus
  tx_pin: GPIO1  # D4 on Wemos D1 Mini
  rx_pin: GPIO3  # D9 on Wemos D1 Mini
  baud_rate: 115200

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 115200

hlk_ld2402:
  id: radar_sensor
  max_distance: 8.5
  disappear_delay: 30

sensor:
  - platform: hlk_ld2402
    hlk_ld2402_id: radar_sensor
    name: "Radar Distance"
    id: radar_distance

binary_sensor:
  - platform: hlk_ld2402
    hlk_ld2402_id: radar_sensor
    name: "Radar Presence"
    type: presence
    device_class: presence

  - platform: hlk_ld2402
    hlk_ld2402_id: radar_sensor
    name: "Radar Movement"
    type: movement

  - platform: hlk_ld2402
    hlk_ld2402_id: radar_sensor
    name: "Radar Micro Movement"
    type: micromovement