# UART configuration for HLK-LD2402
uart:
  id: uart_bus
  tx_pin: GPIO1  # TX0 hardware UART
  rx_pin: GPIO3  # RX0 hardware UART
  baud_rate: 115200
  data_bits: 8
  parity: NONE
  stop_bits: 1

# HLK-LD2402 radar component
external_components:
  - source:
      type: git
      url: https://github.com/mouldybread/hlk_ld2402_esphome
    refresh: 0ms

hlk_ld2402:
  uart_id: uart_bus
  id: radar_sensor
  max_distance: 5.0
  timeout: 5

# Binary sensors
binary_sensor:
  - platform: hlk_ld2402
    id: radar_presence
    name: "Presence"
    device_class: presence
    hlk_ld2402_id: radar_sensor

  - platform: hlk_ld2402
    id: radar_micromovement
    name: "Micromovement"
    device_class: motion
    hlk_ld2402_id: radar_sensor

# Distance sensor
sensor:
  - platform: hlk_ld2402
    id: radar_distance
    name: "Distance"
    hlk_ld2402_id: radar_sensor
    device_class: distance
    unit_of_measurement: "cm"
    accuracy_decimals: 1
    filters:
      - throttle: 2s

# Control buttons - using template buttons instead of custom platform
button:
  - platform: template
    name: "Calibrate"
    on_press:
      - lambda: id(radar_sensor).calibrate();

  - platform: template
    name: "Auto Gain"
    on_press:
      - lambda: id(radar_sensor).enable_auto_gain();

  - platform: template
    name: "Save Config"
    on_press:
      - lambda: id(radar_sensor).save_config();

  - platform: template
    name: "Engineering Mode"
    on_press:
      - lambda: id(radar_sensor).set_work_mode_(4);

# Add status LED if available
status_led:
  pin: GPIO2
