# Basic configuration 
esphome:
  name: radar-ld2402
  friendly_name: Radar Sensor

esp8266:
  board: d1_mini

# UART Configuration (from manual)
uart:
  tx_pin: GPIO1  # D10 on ESP8266
  rx_pin: GPIO3  # D9 on ESP8266

# Remove redundant UART settings since they're handled by the component
# baud_rate: 115200
# data_bits: 8
# parity: NONE
# stop_bits: 1

# HLK-LD2402 configuration
hlk_ld2402:
  id: radar_sensor
  max_distance: 5.0  # in meters, default is 5m
  timeout: 5        # in seconds, default is 5s

# Binary Sensor - Shows if motion/presence is detected
binary_sensor:
  - platform: hlk_ld2402
    name: "Radar Presence"
    presence:
      name: "Radar Presence Detection"
  
  - platform: hlk_ld2402
    name: "Radar Micromovement"
    micromovement:
      name: "Radar Micromovement Detection"

# Distance Sensor - Shows detected target distance
sensor:
  - platform: hlk_ld2402
    name: "Radar Distance"
    distance:
      name: "Target Distance"
      unit_of_measurement: "cm"
      accuracy_decimals: 0

# Optional test buttons
button:
  - platform: template
    name: "Radar Calibrate"
    on_press:
      then:
        - lambda: id(radar_sensor).calibrate();

  - platform: template
    name: "Enable Auto Gain"
    on_press:
      then:
        - lambda: id(radar_sensor).enable_auto_gain();

  - platform: template
    name: "Save Config"
    on_press:
      then:
        - lambda: id(radar_sensor).save_config();

# Optional - set lower log level for production
logger:
  level: INFO
  logs:
    hlk_ld2402: INFO
    uart: DEBUG