external_components:
  - source:
      type: git
      url: https://github.com/mouldybread/hlk_ld2402_esphome
      ref: main

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 115200

hlk_ld2402:
  id: radar_sensor
  max_distance: 8.5
  disappear_delay: 30

sensor:
  - platform: hlk_ld2402
    id: radar_distance
    distance:
      name: "Radar Distance"

binary_sensor:
  - platform: hlk_ld2402
    presence:
      name: "Radar Presence"
      id: radar_presence
    movement:
      name: "Radar Movement"
      id: radar_movement
    micromovement:
      name: "Radar Micro Movement"
      id: radar_micromovement