external_components:
  - source:
      type: git
      url: https://github.com/mouldybread/hlk_ld2402_esphome
      ref: main

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 115200

binary_sensor:
  - platform: hlk_ld2402
    presence:
      name: "Radar Presence"
    movement:
      name: "Radar Movement"
    micromovement:
      name: "Radar Micro Movement"

sensor:
  - platform: hlk_ld2402
    distance:
      name: "Radar Distance"
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 1