external_components:
  - source:
      type: git
      url: https://github.com/mouldybread/hlk_ld2402_esphome
      ref: main

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 115200

hlk_ld2402:
  id: radar_sensor
  max_distance: 8.5
  disappear_delay: 30

sensor:
  - platform: hlk_ld2402
    name: "Radar Distance"
    id: radar_distance
    hlk_ld2402_id: radar_sensor

binary_sensor:
  - platform: hlk_ld2402
    name: "Radar Presence"
    id: radar_presence
    hlk_ld2402_id: radar_sensor
    type: presence

  - platform: hlk_ld2402
    name: "Radar Movement" 
    id: radar_movement
    hlk_ld2402_id: radar_sensor
    type: movement

  - platform: hlk_ld2402
    name: "Radar Micro Movement"
    id: radar_micromovement
    hlk_ld2402_id: radar_sensor
    type: micromovement